AWSTemplateFormatVersion: '2010-09-09'
Description: my first ec2 

Resources:
  MySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH access via port 22 and HTTP access via port 80
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t3.micro
      ImageId: ami-08188a5a4dfdbd573
      KeyName: 9am-we-pass-mum
      SecurityGroups:
        - !Ref MySecurityGroup
      Tags:
        - Key: Name
          Value: croma-srv

